# Generated by Django 5.1.2 on 2024-10-31 11:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_on_or_off', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('white', 'White'), ('dark', 'Dark'), ('default', 'Default')], default='default', max_length=10)),
                ('sound_level', models.IntegerField(default=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(choices=[('Primary 1', 'الصف الأبتدائي الأول'), ('Primary 2', 'الصف الابتدائي الثاني'), ('Primary 3', 'الصف الابتداائي الثالث'), ('Primary 4', 'الصف الابتدائي الرابع'), ('Primary 5', 'الصف الابتدائي الخامس'), ('Primary 6', 'الصف الابتدائي السادس'), ('Prep 1', 'الصف الأعدادي الأول'), ('Prep 2', 'الصق الأعدادي الثاني'), ('Prep 3', 'الصف الأعدادي الثالث'), ('Secondary 1', 'الصف الثانوي الأول'), ('Secondary 2', 'الصف الثانوي الثاني'), ('Secondary 3', 'الصف الثانوي الثالث')], max_length=20)),
                ('learning_type', models.CharField(choices=[('Visual', 'بصري'), ('Auditory', 'سمعي'), ('Kinesthetic', 'تجريبي'), ('Reading/Writing', 'منطقي')], max_length=20)),
                ('first_time_login', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('major', models.CharField(blank=True, choices=[('Science', 'علمي'), ('Arts', 'ادبي'), ('Commerce', 'تجاري'), ('Engineering', 'هندسي')], max_length=20, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.parent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('study_level', models.CharField(choices=[('BEGINNER', 'مبتدئ'), ('INTERMEDIATE', 'متوسط'), ('ADVANCED', 'متقدم'), ('CHALLENGING', 'تنافسي')], max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
