# Generated by Django 5.1.2 on 2024-11-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_studentprofile_academic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_phone', models.CharField(max_length=15)),
                ('applicant_job_title', models.CharField(max_length=100)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('school_name', models.CharField(max_length=255)),
                ('school_country', models.CharField(max_length=100)),
                ('school_phone', models.CharField(max_length=15)),
                ('school_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
