# Generated by Django 5.1.2 on 2024-10-31 11:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('content_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concentration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_concentrated', models.BooleanField()),
                ('emotion', models.CharField(choices=[('angry', 'غاضب'), ('disgust', 'اشمئزاز'), ('fear', 'يخاف'), ('happy', 'سعيد'), ('neutral', 'طبيعي'), ('sad', 'حزين'), ('surprised', 'متفاجئ')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.BigIntegerField()),
                ('exam_type', models.CharField(choices=[('INTRO_EXAM', 'تقويم مبدأي'), ('CONCEPTUAL_EXAM', 'تقويم بنائي علي التمهيد'), ('EXPLANATION_EXAM', 'تقويم بنائي علي الشرح'), ('PREV_REVISION_EXAM', 'تقويم بنائي علي المفهوم السابق'), ('EXERCISES_EXAM', 'تدريبات ديناميكيه'), ('FINAL_ASSESSMENT_EXAM', 'التقويم الختامي')], max_length=30)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('passed', models.BooleanField(default=False)),
                ('total_questions', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='chats.chat')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='content_management.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('learning_phase', models.CharField(choices=[('INTRO_EXAM', 'تقويم مبدأي'), ('CONCEPTUAL_EXAM', 'تقويم بنائي علي التمهيد'), ('EXPLANATION_EXAM', 'تقويم بنائي علي الشرح'), ('PREV_REVISION_EXAM', 'تقويم بنائي علي المفهوم السابق'), ('EXERCISES_EXAM', 'تدريبات ديناميكيه'), ('FINAL_ASSESSMENT_EXAM', 'التقويم الختامي')], max_length=30)),
                ('blooms_level', models.CharField(choices=[('REMEMBER', 'تذكر'), ('UNDERSTAND', 'فهم'), ('APPLY', 'تطبيق'), ('ANALYZE', 'تحليل'), ('EVALUATE', 'تقييم'), ('CREATE', 'ابتكار')], max_length=10)),
                ('learning_type', models.CharField(choices=[('Visual', 'بصري'), ('Auditory', 'سمعي'), ('Kinesthetic', 'تجريبي'), ('Reading/Writing', 'منطقي')], max_length=15)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'اختيار من متعدد'), ('TRUE_FALSE', 'صواب/خطأ'), ('LONG_ANSWER', 'مقالي'), ('SORTING', 'ترتيب')], max_length=15)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'مبتدئ'), ('INTERMEDIATE', 'متوسط'), ('ADVANCED', 'متقدم'), ('CHALLENGING', 'تنافسي')], max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cause', models.TextField(blank=True, null=True)),
                ('question_location_in_video', models.TextField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.lesson')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.topic')),
            ],
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choices', models.JSONField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_question', to='exams.question')),
            ],
        ),
        migrations.CreateModel(
            name='LongAnswerQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correct_answer', models.TextField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='long_answer_question', to='exams.question')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_answer', models.BigIntegerField()),
                ('is_true', models.BooleanField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='exams.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='exams.question')),
            ],
        ),
        migrations.CreateModel(
            name='SortingQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correct_order', models.JSONField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sorting_question', to='exams.question')),
            ],
        ),
        migrations.CreateModel(
            name='TrueFalseQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correct_answer', models.BooleanField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='true_false_question', to='exams.question')),
            ],
        ),
    ]
