# Generated by Django 5.1.2 on 2024-11-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_examquestion_student_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concentration',
            name='emotion',
            field=models.CharField(choices=[('angry', 'غاضب'), ('disgust', 'اشمئزاز'), ('fear', 'يخاف'), ('happy', 'سعيد'), ('neutral', 'طبيعي'), ('sad', 'حزين'), ('surprised', 'متفاجئ'), ('Not_Attentive', 'غير موجود')], max_length=30),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('VARK_EXAM', 'تقويم لتحديد نوع التعلم المفضل'), ('INTRO_EXAM', 'تقويم مبدأي'), ('CONCEPTUAL_EXAM', 'تقويم بنائي علي التمهيد'), ('EXPLANATION_EXAM', 'تقويم بنائي علي الشرح'), ('PREV_REVISION_EXAM', 'تقويم بنائي علي المفهوم السابق'), ('EXERCISES_EXAM', 'تدريبات ديناميكيه'), ('FINAL_ASSESSMENT_EXAM', 'التقويم الختامي')], max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='learning_phase',
            field=models.CharField(choices=[('VARK_EXAM', 'تقويم لتحديد نوع التعلم المفضل'), ('INTRO_EXAM', 'تقويم مبدأي'), ('CONCEPTUAL_EXAM', 'تقويم بنائي علي التمهيد'), ('EXPLANATION_EXAM', 'تقويم بنائي علي الشرح'), ('PREV_REVISION_EXAM', 'تقويم بنائي علي المفهوم السابق'), ('EXERCISES_EXAM', 'تدريبات ديناميكيه'), ('FINAL_ASSESSMENT_EXAM', 'التقويم الختامي')], max_length=30),
        ),
    ]
