# Generated by Django 5.1.2 on 2024-11-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_concentration_emotion_alter_exam_exam_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concentration',
            name='emotion',
            field=models.CharField(choices=[('angry', 'غاضب'), ('disgust', 'اشمئزاز'), ('fear', 'يخاف'), ('happy', 'سعيد'), ('neutral', 'طبيعي'), ('sad', 'حزين'), ('surprised', 'متفاجئ'), ('Not_Attentive', 'غير موجود')], max_length=50),
        ),
    ]
