# Generated by Django 5.1.2 on 2024-10-31 11:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('learning_type', models.CharField(choices=[('Visual', 'بصري'), ('Auditory', 'سمعي'), ('Kinesthetic', 'تجريبي'), ('Reading/Writing', 'منطقي')], max_length=15)),
                ('content_type', models.CharField(choices=[('VIDEO', 'فيديو'), ('DYNAMIC', 'ديناميكي')], max_length=10)),
                ('learning_phase', models.CharField(choices=[('INTRO_CONTENT', 'تمهيد'), ('EXPLANATION_CONTENT', 'شرح الدرس'), ('PREVIOUS_CONTENT_CONTENT', 'مفهوم سابق'), ('PRACTICE_VIDEOS_CONTENT', 'تطبيقات')], max_length=50)),
                ('difficulty_level', models.CharField(choices=[('BEGINNER', 'مبتدئ'), ('INTERMEDIATE', 'متوسط'), ('ADVANCED', 'متقدم'), ('CHALLENGING', 'تنافسي')], max_length=12)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('duration', models.DurationField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.CharField(choices=[('Primary 1', 'الصف الأبتدائي الأول'), ('Primary 2', 'الصف الابتدائي الثاني'), ('Primary 3', 'الصف الابتداائي الثالث'), ('Primary 4', 'الصف الابتدائي الرابع'), ('Primary 5', 'الصف الابتدائي الخامس'), ('Primary 6', 'الصف الابتدائي السادس'), ('Prep 1', 'الصف الأعدادي الأول'), ('Prep 2', 'الصق الأعدادي الثاني'), ('Prep 3', 'الصف الأعدادي الثالث'), ('Secondary 1', 'الصف الثانوي الأول'), ('Secondary 2', 'الصف الثانوي الثاني'), ('Secondary 3', 'الصف الثانوي الثالث')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('base_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_content', to='content_management.basecontent')),
            ],
        ),
        migrations.AddField(
            model_name='basecontent',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.subject'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('topic_difficulty_level', models.CharField(choices=[('BEGINNER', 'مبتدئ'), ('INTERMEDIATE', 'متوسط'), ('ADVANCED', 'متقدم'), ('CHALLENGING', 'تنافسي')], max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.subject')),
            ],
        ),
        migrations.AddField(
            model_name='basecontent',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content_management.topic'),
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('base_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_content', to='content_management.basecontent')),
            ],
        ),
    ]
