# Generated by Django 5.1.2 on 2024-11-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0003_alter_basecontent_learning_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecontent',
            name='learning_phase',
            field=models.CharField(choices=[('INTRO_CONTENT', 'تمهيد'), ('EXPLANATION_CONTENT', 'شرح الدرس'), ('PREVIOUS_CONTENT_CONTENT', 'مفهوم سابق'), ('PRACTICE_VIDEOS_CONTENT', 'تطبيقات'), ('EXERCISES_CONTENT', 'تدريبات ديناميكيه')], max_length=50),
        ),
    ]
